$(document).ready(function () {
    setTimeout(function(){
    $('#video').show().trigger('play');
    $("#imgLeftTop1").show().animate({
        width:'270px',
        opacity:1
    },2000);
    $("#imgLeftTop2").show().animate({
        width:'200px',
        'margin-left':'0px',
        opacity:1
    },3000);
    $("#imgRightTop1").show().animate({
        width:'200px',
        opacity:1
    },4000);
    $("#imgRightTop2").show().animate({
        width:'300px',
        'margin-right':'0px',
        opacity:1
    },5000);
    $("#imgLeftBottom").show().animate({
        height:'332px',
        'margin-top':'0px',
        opacity:1
    },6000);
    $("#imgCenter").show().animate({
        height:'332px',
        width:'520px',
        'margin-top':'0px',
        'margin-left':'20px',
        opacity:1
    },7000);
    $("#imgRightBottom").show().animate({
        height:'332px',
        'margin-top':'0px',
        opacity:1
    },8000);
    },2000)
});